/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libreria_app;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author kdieg
 */
public class CrudAutor extends javax.swing.JFrame {

  /**
   * Creates new form CrudAutor
   */
  public CrudAutor() {
    initComponents();
    setLocationRelativeTo(this);
  }
  
  public boolean validarFecha(String fecha){
    boolean valid = false;
    if((fecha != null && fecha.split("/").length == 3) ||
      (fecha != null && fecha.split("-").length == 3)){
      valid = true;
    }
    return valid;
  }
  
  public String[] parsearFecha(String fecha){
    String[] f = {};
    if(fecha.split("/").length == 3){
      f = fecha.split("/");
    }else{
      f = fecha.split("-");
    }
    return f;
  }
  
  public void resetFields(){
    txtNombre.setText(null);
    txtFecha.setText(null);
    txtPais.setText(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    txtNombre = new javax.swing.JTextField();
    txtFecha = new javax.swing.JTextField();
    txtPais = new javax.swing.JTextField();
    btnList = new javax.swing.JButton();
    btnCreate = new javax.swing.JButton();
    btnEdit = new javax.swing.JButton();
    btnDelete = new javax.swing.JButton();
    btnSearch = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    areaListado = new javax.swing.JTextArea();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    txtId = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setText("NOMBRE AUTOR:");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

    jLabel2.setText("FECHA NACIMIENTO:");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

    jLabel3.setText("PAÏS:");
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
    jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 220, -1));
    jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 70, -1));
    jPanel1.add(txtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, -1));

    btnList.setText("Listar");
    btnList.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnListActionPerformed(evt);
      }
    });
    jPanel1.add(btnList, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

    btnCreate.setText("Crear");
    btnCreate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCreateActionPerformed(evt);
      }
    });
    jPanel1.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

    btnEdit.setText("Editar");
    btnEdit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditActionPerformed(evt);
      }
    });
    jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

    btnDelete.setText("Eliminar");
    btnDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDeleteActionPerformed(evt);
      }
    });
    jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

    btnSearch.setText("Buscar");
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSearchActionPerformed(evt);
      }
    });
    jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

    areaListado.setColumns(20);
    areaListado.setRows(5);
    jScrollPane1.setViewportView(areaListado);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 360, 110));

    jLabel4.setFont(new java.awt.Font("Arimo for Powerline", 1, 14)); // NOI18N
    jLabel4.setText("MANTENEDOR DE AUTORES");
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

    jLabel5.setText("ID:");
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));
    jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 30, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    // TODO add your handling code here:
    String nombre = "";
    int dia, mes, anio;
    Fecha fecha_nacimiento;
    String pais = "";    
    if(!txtNombre.getText().equals("") ||
      !validarFecha(txtFecha.getText()) ||
      !txtPais.getText().equals("")){
      String[] fecha = parsearFecha(txtFecha.getText());
      nombre = txtNombre.getText();
      dia = Integer.parseInt(fecha[0]);
      mes = Integer.parseInt(fecha[1]);
      anio = Integer.parseInt(fecha[2]);
      fecha_nacimiento = new Fecha(dia, mes, anio);
      pais = txtPais.getText();
      
      Autor autor = new Autor(nombre, pais, fecha_nacimiento);
      
      if(DatosAutor.editar(autor)){
        areaListado.setText(areaListado.getText() + autor.toString() + "\n");
        JOptionPane.showMessageDialog(null, "Autor Editado Correctamente");
      }else{
        JOptionPane.showMessageDialog(null, "Error al Editar Autor");
      }
    }else{
      JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
    }
  }//GEN-LAST:event_btnEditActionPerformed

  private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
    // TODO add your handling code here:
    String nombre = "";
    int dia, mes, anio;
    Fecha fecha_nacimiento;
    String pais = "";
    int id;
    
    if(!txtNombre.getText().equals("") ||
      !validarFecha(txtFecha.getText()) ||
      !txtPais.getText().equals("")){
      String[] fecha = parsearFecha(txtFecha.getText());
      nombre = txtNombre.getText();
      dia = Integer.parseInt(fecha[0]);
      mes = Integer.parseInt(fecha[1]);
      anio = Integer.parseInt(fecha[2]);
      fecha_nacimiento = new Fecha(dia, mes, anio);
      pais = txtPais.getText();
      Autor autor = new Autor(nombre, pais, fecha_nacimiento);
      if(DatosAutor.agregar(autor)){
        Autor ultimo = DatosAutor.getAutores().get(DatosAutor.getAutores().size() - 1);
        txtId.setText(String.valueOf(ultimo.getId()));
        areaListado.setText(areaListado.getText() + autor.toString() + "\n");
        JOptionPane.showMessageDialog(null, "Autor creado Correctamente");
      }else{
        JOptionPane.showMessageDialog(null, "Error al crear Autor");
      }
    }else{
      JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
    }
  }//GEN-LAST:event_btnCreateActionPerformed

  private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    // TODO add your handling code here:
    String nombre = "";
    int id;
    if(!txtNombre.getText().equals("") || !txtId.getText().equals("")){
      nombre = txtNombre.getText();
      id = Integer.parseInt(txtId.getText());
      Autor autor = DatosAutor.buscarId(id);
      if(autor != null){
        txtNombre.setText(autor.getNombre());
        txtFecha.setText(autor.getFechaNacimiento().toString());
        txtPais.setText(autor.getPais());
        txtId.setText(String.valueOf(autor.getId()));
        JOptionPane.showMessageDialog(null, "Autor encontrado");
      }else{
        JOptionPane.showMessageDialog(null, "Autor no encontrado");
      }
    }else{
      JOptionPane.showMessageDialog(null, "No puede quedar nombre vacio");
    }
  }//GEN-LAST:event_btnSearchActionPerformed

  private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    // TODO add your handling code here:
    int id;
    if(!txtId.getText().equals("")){
      id = Integer.parseInt(txtNombre.getText());
      
      if(DatosAutor.eliminar(id)){
        resetFields();
        JOptionPane.showMessageDialog(null, "Autor eliminado");
      }else{
        JOptionPane.showMessageDialog(null, "Error al Eliminar o no encontrado");
      }
    }else{
      JOptionPane.showMessageDialog(null, "No puede quedar nombre vacio");
    }
  }//GEN-LAST:event_btnDeleteActionPerformed

  private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
    // TODO add your handling code here:
    areaListado.setText("");
    for(Autor autor : DatosAutor.getAutores()){
      areaListado.setText(areaListado.getText() + autor.toString() + "\n");
    }
  }//GEN-LAST:event_btnListActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CrudAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CrudAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CrudAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CrudAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new CrudAutor().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea areaListado;
  private javax.swing.JButton btnCreate;
  private javax.swing.JButton btnDelete;
  private javax.swing.JButton btnEdit;
  private javax.swing.JButton btnList;
  private javax.swing.JButton btnSearch;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField txtFecha;
  private javax.swing.JTextField txtId;
  private javax.swing.JTextField txtNombre;
  private javax.swing.JTextField txtPais;
  // End of variables declaration//GEN-END:variables
}
