/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libreria_app;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author kdieg
 */
public class CrudLibro extends javax.swing.JFrame {

  /**
   * Creates new form CrudAutor
   */
  public CrudLibro() {
    initComponents();
    llenarComboBoxAutores(DatosAutor.getAutores(), comboAutor);
  }
  
  public static void llenarComboBoxAutores(ArrayList<Autor> arrayList, JComboBox comboBox){
      comboBox.removeAllItems();
      comboBox.addItem("Seleccionar"); 
      for(Autor xx: arrayList){
        comboBox.addItem(xx.getNombre());
      }
    }
  
  public boolean validarFecha(String fecha){
    boolean valid = false;
    if((fecha != null && fecha.split("/").length == 3) ||
      (fecha != null && fecha.split("-").length == 3)){
      valid = true;
    }
    return valid;
  }
  
  public String[] parsearFecha(String fecha){
    String[] f = {};
    if(fecha.split("/").length == 3){
      f = fecha.split("/");
    }else{
      f = fecha.split("-");
    }
    return f;
  }
  
  public void resetFields(){
    txtNombre.setText(null);
    txtEditorial.setText(null);
    txtAnio.setText(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    txtNombre = new javax.swing.JTextField();
    txtEditorial = new javax.swing.JTextField();
    txtAnio = new javax.swing.JTextField();
    btnList = new javax.swing.JButton();
    btnCreate = new javax.swing.JButton();
    btnEdit = new javax.swing.JButton();
    btnDelete = new javax.swing.JButton();
    btnSearch = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    areaListado = new javax.swing.JTextArea();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    txtId = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    comboAutor = new javax.swing.JComboBox<>();
    jLabel7 = new javax.swing.JLabel();
    txtStock = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setText("NOMBRE LIBRO:");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

    jLabel2.setText("EDITORIAL");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

    jLabel3.setText("AÑO PUBLICACIÓN:");
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
    jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 220, -1));
    jPanel1.add(txtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 220, -1));
    jPanel1.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 60, -1));

    btnList.setText("Listar");
    btnList.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnListActionPerformed(evt);
      }
    });
    jPanel1.add(btnList, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

    btnCreate.setText("Crear");
    btnCreate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCreateActionPerformed(evt);
      }
    });
    jPanel1.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

    btnEdit.setText("Editar");
    btnEdit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditActionPerformed(evt);
      }
    });
    jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

    btnDelete.setText("Eliminar");
    btnDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDeleteActionPerformed(evt);
      }
    });
    jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

    btnSearch.setText("Buscar");
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSearchActionPerformed(evt);
      }
    });
    jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

    areaListado.setColumns(20);
    areaListado.setRows(5);
    jScrollPane1.setViewportView(areaListado);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 360, 110));

    jLabel4.setFont(new java.awt.Font("Arimo for Powerline", 1, 14)); // NOI18N
    jLabel4.setText("MANTENEDOR DE LIBROS");
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

    jLabel5.setText("ID:");
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));
    jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 30, -1));

    jLabel6.setText("AUTOR:");
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

    comboAutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
    jPanel1.add(comboAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 220, -1));

    jLabel7.setText("STOCK:");
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
    jPanel1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 30, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    // TODO add your handling code here:
    String nombre = "";
    String nombre_autor;
    Autor autor;
    int autor_index = comboAutor.getSelectedIndex();
    String editorial = "";
    int anio, id, stock;
    if(!txtNombre.getText().equals("") &&
      autor_index != 0 &&
      !txtAnio.getText().equals("") &&
      !txtEditorial.getText().equals("") &&
      !txtStock.getText().equals("") && 
      !txtId.getText().equals("")){
      nombre = txtNombre.getText();
      nombre_autor = String.valueOf(comboAutor.getSelectedItem());
      autor = DatosAutor.buscarNombre(nombre_autor);
      anio =  Integer.parseInt(txtAnio.getText());
      editorial = txtAnio.getText();
      stock = Integer.parseInt(txtStock.getText());
      id = Integer.parseInt(txtId.getText());
      Libro libro = new Libro(nombre, editorial, anio, stock, autor, id);
      if(DatosLibro.editar(libro)){
        areaListado.setText(areaListado.getText() + libro.toString() + "\n");
        JOptionPane.showMessageDialog(null, "Libro Editado Correctamente");
      }else{
        JOptionPane.showMessageDialog(null, "Error al Editar Libro");
      }
    }else{
      JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
    }
  }//GEN-LAST:event_btnEditActionPerformed

  private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
    // TODO add your handling code here:
    String nombre = "";
    String nombre_autor;
    Autor autor;
    int autor_index = comboAutor.getSelectedIndex();
    String editorial = "";
    int anio, id, stock;
    
    if(!txtNombre.getText().equals("") &&
      autor_index != 0 &&
      !txtAnio.getText().equals("") &&
      !txtEditorial.getText().equals("") &&
      !txtStock.getText().equals("")){
      nombre = txtNombre.getText();
      nombre_autor = String.valueOf(comboAutor.getSelectedItem());
      autor = DatosAutor.buscarNombre(nombre_autor);
      anio =  Integer.parseInt(txtAnio.getText());
      editorial = txtAnio.getText();
      stock = Integer.parseInt(txtStock.getText());
      Libro libro = new Libro(nombre, editorial, anio, stock, autor);
      if(DatosLibro.agregar(libro)){
        ArrayList<Libro> libros = DatosLibro.getLibros();
        Libro ultimo = libros.get(libros.size() - 1);
        txtId.setText(String.valueOf(ultimo.getId()));
        areaListado.setText(areaListado.getText() + libro.toString() + "\n");
        JOptionPane.showMessageDialog(null, "Libro creado Correctamente");
      }else{
        JOptionPane.showMessageDialog(null, "Error al crear Libro");
      }
    }else{
      JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
    }
  }//GEN-LAST:event_btnCreateActionPerformed

  private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    // TODO add your handling code here:
    String nombre = "";
    int id;
    if(!txtNombre.getText().equals("") || !txtId.getText().equals("")){
      nombre = txtNombre.getText();
      id = Integer.parseInt(txtId.getText());
      Libro libro = DatosLibro.buscarId(id);
      if(libro != null){
        txtNombre.setText(libro.getNombre());
        comboAutor.setSelectedItem(libro.getAutor().getNombre());
        txtEditorial.setText(libro.getEditorial());
        txtAnio.setText(String.valueOf(libro.getAnioPublicacion()));
        txtStock.setText(String.valueOf(libro.getStock()));
        txtId.setText(String.valueOf(libro.getId()));
        JOptionPane.showMessageDialog(null, "Libro encontrado");
      }else{
        JOptionPane.showMessageDialog(null, "Libro no encontrado");
      }
    }else{
      JOptionPane.showMessageDialog(null, "No puede quedar nombre o Id vacio ");
    }
  }//GEN-LAST:event_btnSearchActionPerformed

  private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    // TODO add your handling code here:
    int id;
    if(!txtId.getText().equals("")){
      id = Integer.parseInt(txtId.getText());
      
      if(DatosLibro.eliminar(id)){
        resetFields();
        JOptionPane.showMessageDialog(null, "Libro eliminado");
      }else{
        JOptionPane.showMessageDialog(null, "Error al Eliminar o no encontrado");
      }
    }else{
      JOptionPane.showMessageDialog(null, "No puede quedar nombre vacio");
    }
  }//GEN-LAST:event_btnDeleteActionPerformed

  private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
    // TODO add your handling code here:
    areaListado.setText("");
    for(Libro libro : DatosLibro.getLibros()){
      areaListado.setText(areaListado.getText() + libro.toString() + "\n");
    }
  }//GEN-LAST:event_btnListActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CrudLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CrudLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CrudLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CrudLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new CrudLibro().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea areaListado;
  private javax.swing.JButton btnCreate;
  private javax.swing.JButton btnDelete;
  private javax.swing.JButton btnEdit;
  private javax.swing.JButton btnList;
  private javax.swing.JButton btnSearch;
  private javax.swing.JComboBox<String> comboAutor;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField txtAnio;
  private javax.swing.JTextField txtEditorial;
  private javax.swing.JTextField txtId;
  private javax.swing.JTextField txtNombre;
  private javax.swing.JTextField txtStock;
  // End of variables declaration//GEN-END:variables
}
