/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libreria_app;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author kdieg
 */
public class LibreriaFrame extends javax.swing.JFrame {

    /**
     * Creates new form Libreria_frame
     */
    public static void llenarComboBoxPersonas(ArrayList<Persona> arrayList, JComboBox comboBox){
        comboBox.removeAllItems();
        comboBox.addItem("Seleccionar");
        for(Persona xx: arrayList){
            comboBox.addItem(xx.getNombre());
        }
    }
    
    public static void llenarComboBoxAutores(ArrayList<Autor> arrayList, JComboBox comboBox){
      comboBox.removeAllItems();
      comboBox.addItem("Seleccionar"); 
      for(Autor xx: arrayList){
        comboBox.addItem(xx.getNombre());
      }
    }
    
    public static void llenarComboBoxLibros(ArrayList<Libro> arrayList, JComboBox comboBox){
        comboBox.removeAllItems();
        comboBox.addItem("Seleccionar");
        for(Libro xx: arrayList){
            comboBox.addItem(xx.getNombre());
        }
    }
    
    public LibreriaFrame() {
        DatosPersona.llenarPersonas();
        DatosAutor.llenarAutores();
        DatosLibro.llenar();
        initComponents();
        setLocationRelativeTo(this);
        llenarComboBoxPersonas(DatosPersona.getPersonas(), cmbCliente);
        llenarComboBoxAutores(DatosAutor.getAutores(), cmbAutores);
        llenarComboBoxLibros(DatosLibro.getLibros(), cmbLibros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    MantenedorAutores = new javax.swing.JInternalFrame();
    jPanel2 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    txtTitle = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    cmbCliente = new javax.swing.JComboBox<>();
    txtRutPersona = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    cmbAutores = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    cmbLibros = new javax.swing.JComboBox<>();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    txtInfoNombre = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    txtInfoEditorial = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    txtInfoAnio = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    txtInfoAutor = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    txtInfoStock = new javax.swing.JTextField();
    btnAsignar = new javax.swing.JButton();
    jLabel12 = new javax.swing.JLabel();
    txtNombrePersona = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    areaInformación = new javax.swing.JTextArea();
    nuevoAutor = new javax.swing.JButton();
    nuevoLibro = new javax.swing.JButton();

    MantenedorAutores.setVisible(true);

    jButton1.setText("Cerrar");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(380, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(308, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addContainerGap())
    );

    javax.swing.GroupLayout MantenedorAutoresLayout = new javax.swing.GroupLayout(MantenedorAutores.getContentPane());
    MantenedorAutores.getContentPane().setLayout(MantenedorAutoresLayout);
    MantenedorAutoresLayout.setHorizontalGroup(
      MantenedorAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    MantenedorAutoresLayout.setVerticalGroup(
      MantenedorAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(204, 255, 153));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txtTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
    txtTitle.setText("Administrador de Libreria");
    jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

    jLabel2.setText("Creación de Pedidos");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

    jLabel1.setText("Rut Persona");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

    cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
    cmbCliente.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbClienteActionPerformed(evt);
      }
    });
    jPanel1.add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 107, -1));

    txtRutPersona.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtRutPersonaActionPerformed(evt);
      }
    });
    jPanel1.add(txtRutPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 111, -1));

    jLabel3.setText("Sel. Autor:");
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

    cmbAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
    cmbAutores.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        cmbAutoresMouseClicked(evt);
      }
    });
    cmbAutores.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbAutoresActionPerformed(evt);
      }
    });
    jPanel1.add(cmbAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 130, -1));

    jLabel4.setText("O existente");
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 50, -1, -1));

    cmbLibros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
    cmbLibros.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbLibrosActionPerformed(evt);
      }
    });
    jPanel1.add(cmbLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 150, -1));

    jLabel5.setText("Sel. Libro:");
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 60, -1));

    jLabel6.setText("Información del libro:");
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

    jLabel7.setText("Nombre:");
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

    txtInfoNombre.setEditable(false);
    txtInfoNombre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtInfoNombreActionPerformed(evt);
      }
    });
    jPanel1.add(txtInfoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 150, -1));

    jLabel8.setText("Editorial:");
    jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

    txtInfoEditorial.setEditable(false);
    txtInfoEditorial.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtInfoEditorialActionPerformed(evt);
      }
    });
    jPanel1.add(txtInfoEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 120, -1));

    jLabel9.setText("Año publicación:");
    jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

    txtInfoAnio.setEditable(false);
    jPanel1.add(txtInfoAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 50, -1));

    jLabel10.setText("Autor:");
    jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

    txtInfoAutor.setEditable(false);
    jPanel1.add(txtInfoAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 140, -1));

    jLabel11.setText("Stock:");
    jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 40, -1));

    txtInfoStock.setEditable(false);
    txtInfoStock.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtInfoStockActionPerformed(evt);
      }
    });
    jPanel1.add(txtInfoStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 30, -1));

    btnAsignar.setText("Asignar libro");
    jPanel1.add(btnAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

    jLabel12.setText("Nombre:");
    jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

    txtNombrePersona.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNombrePersonaActionPerformed(evt);
      }
    });
    jPanel1.add(txtNombrePersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 130, -1));

    jLabel13.setText("Fecha Subscripción: ");
    jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

    jTextField1.setEditable(false);
    jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 100, -1));

    areaInformación.setColumns(20);
    areaInformación.setRows(5);
    jScrollPane1.setViewportView(areaInformación);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 400, 130));

    nuevoAutor.setText("Nuevo Autor");
    nuevoAutor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nuevoAutorActionPerformed(evt);
      }
    });
    jPanel1.add(nuevoAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

    nuevoLibro.setText("Nuevo Libro");
    nuevoLibro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nuevoLibroActionPerformed(evt);
      }
    });
    jPanel1.add(nuevoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClienteActionPerformed

    private void txtRutPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutPersonaActionPerformed

    private void cmbAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAutoresActionPerformed
        // TODO add your handling code here:
        String autor = String.valueOf(cmbAutores.getSelectedItem());
        ArrayList<Libro> librosAutor = DatosLibro.buscarLibrosAutor(autor);
        int index = cmbAutores.getSelectedIndex();
        if(index == 0 || index == -1){
            llenarComboBoxLibros(DatosLibro.getLibros(), cmbLibros);
        }else{
          if(!librosAutor.isEmpty()){
              llenarComboBoxLibros(librosAutor, cmbLibros);
          }else{
              JOptionPane.showMessageDialog(null,"No hay Libros para el autor seleccionado");
          }
          llenarComboBoxLibros(librosAutor, cmbLibros);
        }
    }//GEN-LAST:event_cmbAutoresActionPerformed

    private void txtInfoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInfoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInfoNombreActionPerformed

    private void txtInfoEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInfoEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInfoEditorialActionPerformed

    private void cmbLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLibrosActionPerformed
        // TODO add your handling code here:
        String nombre_libro = String.valueOf(cmbLibros.getSelectedItem());
        Libro libro = DatosLibro.buscarNombre(nombre_libro);
        String editorial = libro.getEditorial();
        String anio = String.valueOf(libro.getAnioPublicacion());
        String autor = libro.getAutor().getNombre();
        String stock = String.valueOf(libro.getStock());
        
        txtInfoNombre.setText(nombre_libro);
        txtInfoEditorial.setText(editorial);
        txtInfoAnio.setText(anio);
        txtInfoAutor.setText(autor);
        txtInfoStock.setText(stock);
    }//GEN-LAST:event_cmbLibrosActionPerformed

    private void txtInfoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInfoStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInfoStockActionPerformed

    private void txtNombrePersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePersonaActionPerformed

  private void nuevoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAutorActionPerformed
    // TODO add your handling code here:
    JFrame frame = new CrudAutor();
    frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    frame.setVisible(true);
  }//GEN-LAST:event_nuevoAutorActionPerformed

  private void cmbAutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbAutoresMouseClicked
    // TODO add your handling code here:
    int selected = cmbAutores.getSelectedIndex();
    llenarComboBoxAutores(DatosAutor.getAutores(), cmbAutores);
    cmbAutores.setSelectedIndex(selected);
  }//GEN-LAST:event_cmbAutoresMouseClicked

  private void nuevoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoLibroActionPerformed
    // TODO add your handling code here:
    JFrame frame = new CrudLibro();
    frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    frame.setVisible(true);
  }//GEN-LAST:event_nuevoLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibreriaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibreriaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibreriaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibreriaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibreriaFrame().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JInternalFrame MantenedorAutores;
  private javax.swing.JTextArea areaInformación;
  private javax.swing.JButton btnAsignar;
  private javax.swing.JComboBox<String> cmbAutores;
  private javax.swing.JComboBox<String> cmbCliente;
  private javax.swing.JComboBox<String> cmbLibros;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JButton nuevoAutor;
  private javax.swing.JButton nuevoLibro;
  private javax.swing.JTextField txtInfoAnio;
  private javax.swing.JTextField txtInfoAutor;
  private javax.swing.JTextField txtInfoEditorial;
  private javax.swing.JTextField txtInfoNombre;
  private javax.swing.JTextField txtInfoStock;
  private javax.swing.JTextField txtNombrePersona;
  private javax.swing.JTextField txtRutPersona;
  private javax.swing.JLabel txtTitle;
  // End of variables declaration//GEN-END:variables
}
